# Generated by Django 3.2.7 on 2021-10-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=16)),
                ('horas', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='Progressos',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('parent', models.IntegerField()),
                ('nome', models.CharField(max_length=64)),
                ('carga', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=64)),
                ('dono', models.CharField(max_length=64)),
                ('prazo', models.DateTimeField(null=True)),
                ('ag', models.BooleanField(null=True)),
                ('importante', models.BooleanField(null=True)),
                ('desc', models.CharField(blank=True, max_length=256)),
                ('comentario', models.CharField(blank=True, max_length=256)),
                ('tag', models.CharField(max_length=64)),
                ('repetir', models.IntegerField(default=0)),
                ('feita', models.BooleanField(default=False)),
                ('fav', models.BooleanField(default=False)),
                ('parent', models.IntegerField(blank=True, default=-1)),
            ],
        ),
    ]
