# Generated by Django 3.2.7 on 2021-09-20 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coisa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 15, 18, 28, 469123, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='coisa',
            name='org',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
