# Generated by Django 3.2.7 on 2021-09-20 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210920_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coisa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 12, 52, 30, 254011)),
        ),
        migrations.AlterField(
            model_name='coisa',
            name='pub',
            field=models.BooleanField(),
        ),
    ]
