# Generated by Django 3.2.7 on 2021-09-22 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210920_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('dono', models.CharField(max_length=64)),
                ('pub', models.BooleanField()),
                ('open', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='coisa',
            name='pub',
        ),
        migrations.AddField(
            model_name='coisa',
            name='abs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coisa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 6, 30, 30, 798714)),
        ),
    ]
