# Generated by Django 3.2.7 on 2021-09-22 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210922_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=64)),
                ('dono', models.CharField(max_length=64)),
                ('pub', models.BooleanField(default=False)),
                ('open', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('parent', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Organizacao',
        ),
        migrations.RenameField(
            model_name='coisa',
            old_name='org',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='coisa',
            name='desc',
        ),
        migrations.AddField(
            model_name='coisa',
            name='grupo',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='coisa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 7, 27, 8, 413788)),
        ),
    ]
