# Generated by Django 3.2.7 on 2021-11-03 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211103_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coisa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 19, 32, 44, 815421)),
        ),
    ]
